version: '3.4'

services:
  traefik:
    image: traefik:v1.5.2-alpine
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - type: bind
        source: ./traefik/traefik.toml
        target: /etc/traefik/traefik.toml
      - type: bind
        source: ./traefik/rules.toml
        target: /etc/traefik/rules.toml
    depends_on:
      - minio
      - mailhole-api
      - mailhole-smtp
  redis:
    image: redis:3.2.11
    ports:
      - 6379:6379
  postgres:
      image: postgres:10.2
      ports:
        - 5432:5432
      env_file:
        - envs/Postgres.env
  minio:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - 9000:9000
    env_file:
      - envs/Minio.env
    command: server /data
  mailhole-api:
    build:
      context: ../
      dockerfile: MailHole.Api-Debug.dockerfile
    env_file:
      - envs/MailHole.API-Debug.env
    volumes:
      - type: bind
        source: ../
        target: /app
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
      - minio
  mailhole-smtp:
    build:
      context: ../
      dockerfile: MailHole.SmtpListener-Debug.dockerfile
    env_file:
      - envs/MailHole.SMTP-Debug.env
    volumes:
          - type: bind
            source: ../
            target: /app
    ports:
      - 1025:1025
    depends_on:
      - postgres
      - redis
      - minio