version: '3.4'

services:
  redis:
    image: redis:3.2.11
    ports:
      - 6379:6379
  minio:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - 9000:9000
    environment:
      - "MINIO_ACCESS_KEY=19OWL0F004QOXHLK8KN4"
      - "MINIO_SECRET_KEY=LVUTKrQgRVY2iZr9iIArdGpXqvSA4gZqxWsif8U8"
    command: server /data
  postgres:
    image: postgres:10.2
    ports:
      - 5432:5432
    env_file:
      - envs/Postgres.env